### ISSUE TITLE
Exception "System.OutOfMemory" while restoring DB.

### ISSUE THREAD

**Issue by tiagossa1** [MySqlBackupNET/MySqlBackup.Net#18]
Hey,
So, I'm making a program that restores databases.

Ficheiro de backup: the .SQL file to restore.
Servidor: server.
Base de dados: Database.
Utilizador: user.
Porta: port.
Button "Restaurar" is "Restore".
I'm using your Mysql.data and Mysql.backup DLLs (MySQL Connector).

While it's restoring, it throws a 'System.OutOfMemoryException'. It shouldn't, I have 4GB of RAM, so I'm supposing that it's not a RAM problem.

Snippet of my code: https://ghostbin.com/paste/twq2d.
Stacktrace: https://ghostbin.com/paste/o5q2o 
My SQL file is about 736MB.

(Using SharpDevelop, I can't debug line by line with F11, I don't know why though...)
![capturar](https://user-images.githubusercontent.com/26775757/37479174-efacd76a-2873-11e8-84e9-dc9b50fe3adc.PNG)

**Comment by adriancs2** [comment]
I'm thinking maybe it it caused by the immutable behavior of string in .NET causing too many strings accumulated in memory.
 https://stackoverflow.com/questions/2365272/why-net-string-is-immutable

So, I have tried an attempt by manually calling the garbage collector to clear the unused strings .

I have added this line
```C#
GC.Collect();
```
at the method `Import_AppendLineAndExecute(string line)` at line 1219 (MySqlBackup.cs)
```C#
void Import_AppendLineAndExecute(string line)
{
    _sbImport.AppendLine(line);
    if (!line.EndsWith(_delimiter))
        return;

    _mySqlScript.Query = _sbImport.ToString();
    _mySqlScript.Delimiter = _delimiter;
    _mySqlScript.Execute();
    _sbImport = new StringBuilder();

    GC.Collect();
}
```
I have attached the modified MySqlBackup.NET, you can download it and try again with your solution and see if the error still exists or not.
[MySqlBackup_Debug_Issue18_V1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/1824567/MySqlBackup_Debug_Issue18_V1.zip)

**Comment by tiagossa1** [comment]
Hey,
Thanks, I belive that is working now. I've made my tests with big .SQL dumps and didn't have an exception.
Thanks again :)

**Comment by adriancs2** [comment]
I'm glad it works :)
by the way, I'm interest to know how much time does your program took to complete a restore a 736MB size of dump file with MySqlBackup.NET in your environment. Can you share this info with me?

**Comment by tiagossa1** [comment]
of course, @adriancs2 .

dump file is 770 MB.
it took me 22m 55s to complete the dump.

The table had 1GB +/-

**Comment by adriancs2** [comment]
thanks :)
