### ISSUE TITLE
TINYINT broken values on restore

### ISSUE THREAD

**Issue by souleime** [MySqlBackupNET/MySqlBackup.Net#25]
Backup file when restored messes up tinyint(1) values
e.g. 2 becomes 1 instead of 2
e.g. 3 becomes 1 instead of 3
But tinyint(4) values remain the same as it should

**Comment by adriancs2** [comment]
I have run a test and unable to repeat the error. Please provide more info or upload a sample project that will repeat the error. Following is the test that I have run. Both backup and restore did not generate the error:
```
DROP TABLE IF EXISTS `tb1`;
CREATE TABLE IF NOT EXISTS `tb1` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `aa` tinyint(1) unsigned DEFAULT NULL,
  `bb` tinyint(2) unsigned DEFAULT NULL,
  `cc` tinyint(4) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- 
-- Dumping data for table tb1
-- 

/*!40000 ALTER TABLE `tb1` DISABLE KEYS */;
INSERT INTO `tb1`(`id`,`aa`,`bb`,`cc`) VALUES
(1,1,1,1),
(2,2,2,2),
(3,3,3,3),
(4,4,4,4);
/*!40000 ALTER TABLE `tb1` ENABLE KEYS */;
```

**Comment by souleime** [comment]
Please try exactly the structure but not with unsigned tinyint fields

**Comment by adriancs2** [comment]
Hi, I am able to regenerate the error after removing the UNSIGNED flag. 

The error is caused by data conversion / data type mapping performed by MySql.Data.DLL. I found that MySql.Data.DLL automatically convert MySQL data type TINYINT(1) into Boolean (.NET). Therefore, it will be either TRUE or FALSE after conversion.

To resolve this problem, you can add another connection string option:
```
treattinyasboolen=false;
```
Example: 
```
server=localhost;user=root;pwd=1234;database=test1;treattinyasboolean=false;
```
For more info on the connection string option, you can refer to
https://dev.mysql.com/doc/connector-net/en/connector-net-6-10-connection-options.html

Default value of treattinyasboolen = true.
When setting treattinyasboolen=true, TINYINT(1) = boolean
When setting treattinyasboolen=false, TINYINT(1) will be treated as INT

For more info on the Numeric Type data handling, you can refer to
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html
>> at the section explaining "BOOL, BOOLEAN", which is equivalent to TINYINT(1) by default.

**Comment by souleime** [comment]
Thank you so much for your help I will close the issue since it is not related with the library and for sure it is not a bug

**Comment by tedebus** [comment]
Please note that the correct option is not:
`treattinyasboolean=false`
but is
**`TreatTinyAsBoolean=false`**

MySql is case sensitive!

**Comment by adriancs2** [comment]
@tedebus no, it is not case sensitive. I have applied the lowercase connection string option in lots of my projects.

**Comment by tedebus** [comment]
It's very strange. On my version (5.7) it give me an error if I use all
lowercase options in connection string...


Il ven 8 mar 2019, 13:26 Adrian Voo <notifications@github.com> ha scritto:

**Comment by adriancs2** [comment]
Do you notice that all connection string options presented in tutorials, wiki pages, demo projects of this project are all in lower case?

**Comment by tedebus** [comment]
Well, I see.
But this is not true for my one.
Because, as said, If I use treattinyasboolean I receive "unknown option" error. If I use TreatTinyAsBoolean it works.
Same for other options.
It's not a theory of mine and I believe to you, but it's what happens to me.
So, to avoid eventual future errors, I prefer to use options as documented in the link you provided.
