### ISSUE TITLE
MySql.Data.dll Problem

### ISSUE THREAD

**Issue by hirocsingh** [MySqlBackupNET/MySqlBackup.Net#32]
MySqlBackup Method not working in .NET Framework 4.5.2

**Comment by adriancs2** [comment]
You have provided too little clues and insufficient info to identify or guess your problem. Try provide more details.

**Comment by hirocsingh** [comment]
string constring = "server=localhost;user=root;pwd=qwerty;database=test;";
string file = "C:\\backup.sql";
using (MySqlConnection conn = new MySqlConnection(constring))
{
    using (MySqlCommand cmd = new MySqlCommand())
    {
        using (MySqlBackup mb = new MySqlBackup(cmd))
        {
            cmd.Connection = conn;
            conn.Open();
            mb.ImportFromFile(file);
            conn.Close();
        }
    }
}


**The above line of code doesn't compile when working with .NET 4.5.2.**
>> Even if I add MySql.Data.DLL reference to my Project.

**Comment by adriancs2** [comment]
I think you might have referenced the wrong .NET version of DLL.

**Comment by hirocsingh** [comment]
I referred to Version 6.x.x till 8.x.x (Latest Stable) all of them didn't work.

**Comment by adriancs2** [comment]
You may attach a simple sample project that will generate the error. I can have a look on it.

**Comment by hirocsingh** [comment]
This happened during a project i was working on, since i couldn't figure out what is wrong, I switched to SQL Server. But if you want to test it I can direct you to my project and you would just need to make few changes in one of the Methods to generate Error. [My Project](https://github.com/hirocsingh/FileWatcher-for-DB-Restore). Just change the method **private void RestoreDatabase()** with the above lines of code in this Issue thread. Thanks.

**Comment by hirocsingh** [comment]
in **Service.cs**

**Comment by adriancs2** [comment]
I have downloaded your the sample project that you have provided.

Here is the problem:

Every release or every build of MySqlBackup.NET is bound with specific version of MySql.Data.DLL.

Problem 1: If there is a new version of MySql.Data.DLL, MySqlBackup.NET is required to recompiled / rebuilt.

Problem 2: If you reference a newer target platform of MySqlBackup.NET (i.e. version 4.6 or 4.7), it will not work in your project. This is because your project has a lower target platform 4.5.2. Version 4.6 of DLL won't work in 4.5.2.

Steps to resolve this problem:

Note 1: You must use a .net platform version of MySqlBackup.NET build at .net framework 4.5.2 or lower (i.e. 4.0 or 4.5)

Note 2: If you download the pre-built version MySqlBackup.NET, you must use the specific version of MySql.Data.DLL which bound together with it. It is usually located at the same folder of the MySqlBackup.NET inside the downloaded zip. 

Note 3: If you wish to use your downloaded version or NUGET version of MySql.Data.DLL, then you need to do either one of the following options:

Option 1: Include the source code of MySqlBackup.NET directly into your project, which I personally STRONGLY RECOMMENDED.

Option 2: Recompile or rebuild MySqlBackup.NET with your version of MySql.Data.DLL.

You may read more about at the following wiki page:
https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/How-to-Add-This-Library-into-Your-Project


=================
By the way, I would like to talk a little bit about the sample project that you have presented.

The presented project don't have elements of MySqlBackup.NET. It is a normal error free project. It requires me to manually modify your project to re-generate the error that match to your description which I even not 100% sure that replicates your original of problem. It is usually not your working project.

That is not a good example of "Sample Project" for presenting error. A "sample project" refers here should be a very tiny program with one purpose only >> to demonstrate or to re-produce the error.

**Comment by hirocsingh** [comment]
Alright, Understood, I will have to regenerate the errors.  Closing this issue for now, will reopen it when I'll have all the required details. Thanks.
