### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by cjonstrup** [MySqlBackupNET/MySqlBackup.Net#4]
Hi,

After doing a export/import from memorystream my memory usage is more than 400MB

using (MemoryStream ms = new MemoryStream())
{
  //export
 
  //import

}

**Comment by adriancs2** [comment]
yes, because of the natural characteristic of how .NET Framework handle the memory usage. Every objects creates by .NET will be temporary stayed in the memory. All the objects (string, class, values, etc) will be eventually be recycled by Garbage Collector when .NET believes that all the references and values are not more in use, but it is hard to tell when the Garbage Collector will start to clean up the resources. Therefore, you can manually tell the .NET Garbage Collector to free the memory by executing the following:
```
GC.Collect();
```
