### ISSUE TITLE
Differential and Incrementale backup

### ISSUE THREAD

**Issue by LemmyK6** [MySqlBackupNET/MySqlBackup.Net#59]
Can you please add the differential and incrementale backup to your library?

**Comment by adriancs2** [comment]
This has to be handle manually. 1 of the suggestion that you can consider is by adding a column for time stamp. Use the time stamp to help you to do the incremental backup. Then you can use [this guide](https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/Conditional-Rows-Export-for-Each-Table) to do the conditional rows export.

It is however not recommended to do it this way, because it can be easily messed up the destination database. 

I think the best way to handle this is through you programming language, like C#, not through this library.

You might also want to consider to use MySql Replication (https://severalnines.com/resources/tutorials/mysql-replication-high-availability-tutorial)
