### ISSUE TITLE
System.Threading.ThreadPool Downgrade?

### ISSUE THREAD

**Issue by da3dsoul** [MySqlBackupNET/MySqlBackup.Net#61]
I upgraded this package to the latest stable while cleaning up unused references in older project.
I removed the MySQL.Data package to let Nuget implicitly decide on the version.

Now I have this:
```
  Shoko.Server.csproj: [NU1605] Detected package downgrade: System.Threading.ThreadPool from 4.3.0 to 4.0.10. Reference the package directly from the project to select a different version. 
 Shoko.Server -> MySqlBackup.NET 2.3.1 -> MySql.Data 8.0.17 -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Threading.ThreadPool (>= 4.3.0) 
 Shoko.Server -> MySqlBackup.NET 2.3.1 -> MySql.Data 8.0.17 -> SSH.NET 2016.1.0 -> System.Threading.ThreadPool (>= 4.0.10)
```

I obviously plan to do what it says, but the fact that this happens is annoying. As far as I can tell, it's not actually the fault of this project, but MySQL,Data. Unfortunately, I think that's closed source, so I can't do anything about it. If you explicitly reference the version, it should cascade and prevent the need for users to do it, though...I think.

**Comment by adriancs2** [comment]
During compilation of the DLL, this project was bound with specific version of MySql.Data. I still unsure how to unbound with specific version MySql.Data, so that MySqlBackup.NET can freely work with any version of MySql.Data.

So, in order to keep up the new releases of MySql.Data, this project need to be continuously re-released even without any major changes.

I believe there should be a workaround for this problem, but I'm unable to find one at the moment.

If you do find the solution, you may reply at the post. Thanks.

**Comment by adriancs2** [comment]
I will release a new nuget package later today.

**Comment by adriancs2** [comment]
Hi, new version of nuget package is released.

**Comment by da3dsoul** [comment]
Thanks
