### ISSUE TITLE
System.Collections.Generic.KeyNotFound Exception

### ISSUE THREAD

**Issue by mariusvaida** [MySqlBackupNET/MySqlBackup.Net#76]
With the latest version of MariaDB the backup function is causing an exception, even in your test app.
The exception is located at: mysql.data.mysqlclient.mysqlfield.setfieldencoding()
![Screenshot_3](https://user-images.githubusercontent.com/19683063/130948698-e833d1ab-efc9-41b1-a3e7-6ad2fc09d8c2.png)
 exception

**Comment by adriancs2** [comment]
Hi, the character set of "utf8mb3" is not supported in MySQL, therefore the dot net connector MySQL.DATA.DLL does not include the collection for "utf8mb3". You may try to change your database character set of "utf8mb3" to "utf8mb4".

More information for list supported character set:
https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html

**Comment by mariusvaida** [comment]
You are right! Manually editing the db and setting to utf8mb4 fixed the issue. The problem with the latest version of MariaDB will persist in the future as it uses by default utf8mb3 dor utf8 and until now i'm unable to change the default. 
Thank you very much!

**Comment by adriancs2** [comment]
Hi @mariusvaida , I have released another version of MySqlBackup.NET for MySqlConnector (MIT), so you can try use this version to run a test and see if MySqlConnector has any issue with utf8mb3.

Here is the nuget for MySqlConnector:
PM> Install-Package MySqlBackup.NET.MySqlConnector
https://www.nuget.org/packages/MySqlBackup.NET.MysqlConnector/

You're recommended to test this on a new blank project, this is because MySqlConnector uses the same namespace as MySql.Data.DLL, and thig might crashes your project.
