### ISSUE TITLE
After upgrading to 2.3.8, the prompt file does not exist

### ISSUE THREAD

**Issue by qcjxberin** [MySqlBackupNET/MySqlBackup.Net#99]
![image](https://user-images.githubusercontent.com/5792218/223647250-7cca6fa2-f8e3-4876-bdb1-9baaec91e496.png)

**Comment by adriancs2** [comment]
It might caused by compilation failure. The connector with MySqlData is using MySql.Data 8.0.32 which might has some issues in some specific situation.

I can think of 2 solutions:

**Solution 1: use MySqlBackup.NET with MySqlConnector**
https://www.nuget.org/packages/MySqlBackup.NET.MySqlConnector/
MySqlConnector is more stable than MySql.Data.

**Solution 2: Downgrade MySqlBackup.NET to version 2.3.7**
Here's the guide:
https://stackoverflow.com/questions/10206090/how-can-i-install-an-older-version-of-a-package-via-nuget

**Comment by qcjxberin** [comment]
Ok，Thinks，I Will Use [MySqlBackup.NET.MySqlConnector/](https://www.nuget.org/packages/MySqlBackup.NET.MySqlConnector/)
